[managed_nodes]
slurm-ctrl ansible_host=10.99.239.155
slurm-c01 ansible_host=10.99.239.82
slurm-c02 ansible_host=10.99.239.80
slurm-c03 ansible_host=10.99.239.19

[managed_nodes:vars]
ansible_user=mitac
ansible_python_interpreter=/usr/bin/python3
